"""overstay billing

Revision ID: 8a3243df460a
Revises: 2ccc0b3e21d3
Create Date: 2026-09-19 15:59:54.887568+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '8a3243df460a'
down_revision: str | None = '2ccc0b3e21d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate also wanted to drop the server defaults on
    # `arrival_codes.attempts` and `parking_spaces.requires_arrival_code`; those
    # are deliberate, so that part is not applied. Every column added here
    # carries a default for the same reason — these tables already have rows.
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('overstay_minutes', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('overstay_amount', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('overstay_paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('purpose', sa.String(length=20), nullable=False, server_default='BOOKING'))
    op.create_index(op.f('ix_payments_purpose'), 'payments', ['purpose'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_purpose'), table_name='payments')
    op.drop_column('payments', 'purpose')
    op.drop_column('bookings', 'overstay_paid_at')
    op.drop_column('bookings', 'overstay_amount')
    op.drop_column('bookings', 'overstay_minutes')
    # ### end Alembic commands ###
