"""arrival verification

Revision ID: 2a5bdfbc7ad8
Revises: dca28ddb7853
Create Date: 2026-09-19 13:41:28.994953+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2a5bdfbc7ad8'
down_revision: str | None = 'dca28ddb7853'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrival_codes',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_arrival_codes_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_arrival_codes'))
    )
    op.create_index(op.f('ix_arrival_codes_booking_id'), 'arrival_codes', ['booking_id'], unique=False)
    op.create_index('uq_arrival_codes_booking', 'arrival_codes', ['booking_id'], unique=True)
    # Existing listings must get a value, so the column needs a server default.
    # Off by default: turning it on is a deliberate choice by a provider whose
    # gate has nobody at it.
    op.add_column(
        'parking_spaces',
        sa.Column('requires_arrival_code', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking_spaces', 'requires_arrival_code')
    op.drop_index('uq_arrival_codes_booking', table_name='arrival_codes')
    op.drop_index(op.f('ix_arrival_codes_booking_id'), table_name='arrival_codes')
    op.drop_table('arrival_codes')
    # ### end Alembic commands ###
