"""parking bays

Revision ID: 2ccc0b3e21d3
Revises: 2a5bdfbc7ad8
Create Date: 2026-09-19 15:42:32.706246+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '2ccc0b3e21d3'
down_revision: str | None = '2a5bdfbc7ad8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_bays',
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('col_index', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('slot_index >= 0', name=op.f('ck_parking_bays_bay_slot_index_non_negative')),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_parking_bays_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_bays'))
    )
    op.create_index(op.f('ix_parking_bays_parking_space_id'), 'parking_bays', ['parking_space_id'], unique=False)
    op.create_index('uq_parking_bays_space_slot', 'parking_bays', ['parking_space_id', 'slot_index'], unique=True)
    # NOTE: autogenerate also wanted to drop the server defaults on
    # `arrival_codes.attempts` and `parking_spaces.requires_arrival_code`. Those
    # are deliberate — they are what let those NOT NULL columns be added to
    # tables that already had rows — so that part is not applied here.

    # Backfill: every existing listing gets a bay per slot, or its picker would
    # be empty. Labels match parking_bays' default scheme (A-1..A-6, B-1...).
    op.execute(
        '''
        INSERT INTO parking_bays
            (id, parking_space_id, slot_index, label, row_index, col_index, is_active,
             created_at, updated_at)
        SELECT
            gen_random_uuid(),
            s.id,
            g.i,
            chr(65 + (g.i / 6)) || '-' || ((g.i % 6) + 1),
            g.i / 6,
            g.i % 6,
            true,
            now(),
            now()
        FROM parking_spaces s
        CROSS JOIN LATERAL generate_series(0, GREATEST(s.total_slots, 1) - 1) AS g(i)
        WHERE g.i < 156
        '''
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_parking_bays_space_slot', table_name='parking_bays')
    op.drop_index(op.f('ix_parking_bays_parking_space_id'), table_name='parking_bays')
    op.drop_table('parking_bays')
    # ### end Alembic commands ###
