"""initial schema

Revision ID: dca28ddb7853
Revises: 
Create Date: 2026-09-18 08:13:42.138095+00:00
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'dca28ddb7853'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # btree_gist lets a GiST exclusion constraint mix equality on scalar columns
    # (parking_space_id, slot_index) with range overlap on `period`. Without it
    # the bookings table cannot be created.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('profile_photo_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('RENTER', 'PROVIDER', 'ADMIN', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='userstatus', native_enum=False, length=32), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('webhook_events',
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events'))
    )
    op.create_index('uq_webhook_events_gateway_event', 'webhook_events', ['gateway', 'event_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('emailed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_event'), 'notifications', ['event'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], name=op.f('fk_platform_settings_updated_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_platform_settings'))
    )
    op.create_table('providers',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_type', sa.Enum('INDIVIDUAL', 'SOCIETY', name='providertype', native_enum=False, length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING_VERIFICATION', 'VERIFIED', 'REJECTED', name='verificationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('authority_declared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='providerstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_providers_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    sa.UniqueConstraint('user_id', name=op.f('uq_providers_user_id'))
    )
    op.create_index(op.f('ix_providers_verification_status'), 'providers', ['verification_status'], unique=False)
    op.create_table('vehicles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.Enum('BIKE', 'CAR', 'SUV', name='vehicletype', native_enum=False, length=32), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('make_model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_vehicles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles'))
    )
    op.create_index(op.f('ix_vehicles_user_id'), 'vehicles', ['user_id'], unique=False)
    op.create_index('uq_vehicles_user_registration', 'vehicles', ['user_id', 'registration_number'], unique=True)
    op.create_table('parking_spaces',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parking_type', sa.Enum('OPEN', 'COVERED', 'BASEMENT', 'GARAGE', name='parkingtype', native_enum=False, length=32), nullable=False),
    sa.Column('vehicle_types', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('address_line', sa.String(length=300), nullable=False),
    sa.Column('landmark', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=12), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('access_instructions', sa.Text(), nullable=True),
    sa.Column('total_slots', sa.Integer(), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'PUBLISHED', 'PAUSED', 'REJECTED', 'SUSPENDED', name='listingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('authority_confirmed', sa.Boolean(), nullable=False),
    sa.Column('rating_average', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name=op.f('ck_parking_spaces_latitude_range')),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name=op.f('ck_parking_spaces_longitude_range')),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_parking_spaces_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_spaces'))
    )
    op.create_index(op.f('ix_parking_spaces_city'), 'parking_spaces', ['city'], unique=False)
    op.create_index('ix_parking_spaces_lat_lon', 'parking_spaces', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_parking_spaces_parking_type'), 'parking_spaces', ['parking_type'], unique=False)
    op.create_index(op.f('ix_parking_spaces_provider_id'), 'parking_spaces', ['provider_id'], unique=False)
    op.create_index(op.f('ix_parking_spaces_status'), 'parking_spaces', ['status'], unique=False)
    op.create_index('ix_parking_spaces_status_city', 'parking_spaces', ['status', 'city'], unique=False)
    op.create_table('payouts',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PAID', 'FAILED', name='payoutstatus', native_enum=False, length=32), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_payouts_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payouts'))
    )
    op.create_index(op.f('ix_payouts_provider_id'), 'payouts', ['provider_id'], unique=False)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('societies',
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_societies_provider_id_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_societies')),
    sa.UniqueConstraint('provider_id', name=op.f('uq_societies_provider_id'))
    )
    op.create_table('availability_blocks',
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_availability_blocks_end_after_start')),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_availability_blocks_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_blocks'))
    )
    op.create_index(op.f('ix_availability_blocks_parking_space_id'), 'availability_blocks', ['parking_space_id'], unique=False)
    op.create_index('ix_availability_blocks_space_window', 'availability_blocks', ['parking_space_id', 'start_at', 'end_at'], unique=False)
    op.create_table('availability_rules',
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_availability_rules_day_of_week_range')),
    sa.CheckConstraint('end_minute > 0 AND end_minute <= 1440', name=op.f('ck_availability_rules_end_minute_range')),
    sa.CheckConstraint('end_minute > start_minute', name=op.f('ck_availability_rules_end_after_start')),
    sa.CheckConstraint('start_minute >= 0 AND start_minute < 1440', name=op.f('ck_availability_rules_start_minute_range')),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_availability_rules_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availability_rules'))
    )
    op.create_index(op.f('ix_availability_rules_parking_space_id'), 'availability_rules', ['parking_space_id'], unique=False)
    op.create_index('ix_availability_rules_space_day', 'availability_rules', ['parking_space_id', 'day_of_week'], unique=False)
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=20), nullable=False),
    sa.Column('renter_id', sa.UUID(), nullable=False),
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', postgresql.TSTZRANGE(), sa.Computed("tstzrange(start_at, end_at, '[)')", persisted=True), nullable=False),
    sa.Column('unit', sa.Enum('HOURLY', 'DAILY', 'MONTHLY', name='pricingunit', native_enum=False, length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('provider_earning', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING_PAYMENT', 'PENDING_APPROVAL', 'CONFIRMED', 'ACTIVE', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'DISPUTED', 'REJECTED', name='bookingstatus', native_enum=False, length=32), nullable=False),
    sa.Column('hold_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by_id', sa.UUID(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('renter_notes', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('parking_space_id'), '='), (sa.column('slot_index'), '='), (sa.column('period'), '&&'), where=sa.text("status IN ('PENDING_PAYMENT', 'PENDING_APPROVAL', 'CONFIRMED', 'ACTIVE', 'DISPUTED')"), using='gist', name='no_overlapping_bookings'),
    sa.CheckConstraint('end_at > start_at', name=op.f('ck_bookings_end_after_start')),
    sa.CheckConstraint('slot_index >= 0', name=op.f('ck_bookings_slot_index_non_negative')),
    sa.CheckConstraint('total_amount >= 0', name=op.f('ck_bookings_total_non_negative')),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['users.id'], name=op.f('fk_bookings_cancelled_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_bookings_parking_space_id_parking_spaces'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], name=op.f('fk_bookings_provider_id_providers'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['renter_id'], ['users.id'], name=op.f('fk_bookings_renter_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_bookings_vehicle_id_vehicles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings'))
    )
    op.create_index(op.f('ix_bookings_hold_expires_at'), 'bookings', ['hold_expires_at'], unique=False)
    op.create_index(op.f('ix_bookings_parking_space_id'), 'bookings', ['parking_space_id'], unique=False)
    op.create_index(op.f('ix_bookings_provider_id'), 'bookings', ['provider_id'], unique=False)
    op.create_index('ix_bookings_provider_start', 'bookings', ['provider_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index(op.f('ix_bookings_renter_id'), 'bookings', ['renter_id'], unique=False)
    op.create_index('ix_bookings_renter_start', 'bookings', ['renter_id', 'start_at'], unique=False)
    op.create_index(op.f('ix_bookings_start_at'), 'bookings', ['start_at'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_status_start', 'bookings', ['status', 'start_at'], unique=False)
    op.create_table('parking_photos',
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_parking_photos_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_photos'))
    )
    op.create_index(op.f('ix_parking_photos_parking_space_id'), 'parking_photos', ['parking_space_id'], unique=False)
    op.create_table('parking_prices',
    sa.Column('parking_space_id', sa.UUID(), nullable=False),
    sa.Column('unit', sa.Enum('HOURLY', 'DAILY', 'MONTHLY', name='pricingunit', native_enum=False, length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_parking_prices_amount_positive')),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_parking_prices_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parking_prices'))
    )
    op.create_index(op.f('ix_parking_prices_parking_space_id'), 'parking_prices', ['parking_space_id'], unique=False)
    op.create_index('uq_parking_prices_space_unit', 'parking_prices', ['parking_space_id', 'unit'], unique=True)
    op.create_table('society_agreements',
    sa.Column('society_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('revenue_share_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('parking_space_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', name='agreementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['society_id'], ['societies.id'], name=op.f('fk_society_agreements_society_id_societies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_society_agreements'))
    )
    op.create_index(op.f('ix_society_agreements_society_id'), 'society_agreements', ['society_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=False),
    sa.Column('gateway_order_id', sa.String(length=120), nullable=False),
    sa.Column('gateway_payment_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'AUTHORIZED', 'CAPTURED', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', name='paymentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_booking_status', 'payments', ['booking_id', 'status'], unique=False)
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index('uq_payments_gateway_order', 'payments', ['gateway', 'gateway_order_id'], unique=True)
    op.create_table('payout_bookings',
    sa.Column('payout_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payout_bookings_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], name=op.f('fk_payout_bookings_payout_id_payouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payout_id', 'booking_id', name=op.f('pk_payout_bookings')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_payout_bookings_booking_id'))
    )
    op.create_table('reports',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.Enum('SPACE_UNAVAILABLE', 'SPACE_OCCUPIED', 'ACCESS_PROBLEM', 'PROPERTY_DAMAGE', 'PAYMENT_PROBLEM', 'OTHER', name='issuetype', native_enum=False, length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='reportstatus', native_enum=False, length=32), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('resolved_by_id', sa.UUID(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reports_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_reports_reporter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], name=op.f('fk_reports_resolved_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_booking_id'), 'reports', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reports_issue_type'), 'reports', ['issue_type'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('reviews',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.Enum('SPACE', 'RENTER', name='reviewsubject', native_enum=False, length=32), nullable=False),
    sa.Column('parking_space_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parking_space_id'], ['parking_spaces.id'], name=op.f('fk_reviews_parking_space_id_parking_spaces'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_reviews_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_index(op.f('ix_reviews_author_id'), 'reviews', ['author_id'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=False)
    op.create_index('ix_reviews_space_created', 'reviews', ['parking_space_id', 'created_at'], unique=False)
    op.create_index('uq_reviews_booking_subject', 'reviews', ['booking_id', 'subject'], unique=True)
    op.create_table('refunds',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('gateway_refund_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='refundstatus', native_enum=False, length=32), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('gateway_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds'))
    )
    op.create_index(op.f('ix_refunds_payment_id'), 'refunds', ['payment_id'], unique=False)
    op.create_table('report_photos',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_photos_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_photos'))
    )
    op.create_index(op.f('ix_report_photos_report_id'), 'report_photos', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_photos_report_id'), table_name='report_photos')
    op.drop_table('report_photos')
    op.drop_index(op.f('ix_refunds_payment_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index('uq_reviews_booking_subject', table_name='reviews')
    op.drop_index('ix_reviews_space_created', table_name='reviews')
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_author_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_issue_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_booking_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('payout_bookings')
    op.drop_index('uq_payments_gateway_order', table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_index('ix_payments_booking_status', table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_society_agreements_society_id'), table_name='society_agreements')
    op.drop_table('society_agreements')
    op.drop_index('uq_parking_prices_space_unit', table_name='parking_prices')
    op.drop_index(op.f('ix_parking_prices_parking_space_id'), table_name='parking_prices')
    op.drop_table('parking_prices')
    op.drop_index(op.f('ix_parking_photos_parking_space_id'), table_name='parking_photos')
    op.drop_table('parking_photos')
    op.drop_index('ix_bookings_status_start', table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_at'), table_name='bookings')
    op.drop_index('ix_bookings_renter_start', table_name='bookings')
    op.drop_index(op.f('ix_bookings_renter_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_index('ix_bookings_provider_start', table_name='bookings')
    op.drop_index(op.f('ix_bookings_provider_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_parking_space_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hold_expires_at'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_availability_rules_space_day', table_name='availability_rules')
    op.drop_index(op.f('ix_availability_rules_parking_space_id'), table_name='availability_rules')
    op.drop_table('availability_rules')
    op.drop_index('ix_availability_blocks_space_window', table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_parking_space_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')
    op.drop_table('societies')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_provider_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index('ix_parking_spaces_status_city', table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_status'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_provider_id'), table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_parking_type'), table_name='parking_spaces')
    op.drop_index('ix_parking_spaces_lat_lon', table_name='parking_spaces')
    op.drop_index(op.f('ix_parking_spaces_city'), table_name='parking_spaces')
    op.drop_table('parking_spaces')
    op.drop_index('uq_vehicles_user_registration', table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_user_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_providers_verification_status'), table_name='providers')
    op.drop_table('providers')
    op.drop_table('platform_settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_event'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_webhook_events_gateway_event', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
