#!/usr/bin/env bash
# Generate a production .env with real secrets.
#
#     ./scripts/generate-production-env.sh > .env.production
#
# Everything this can generate, it generates. Everything it cannot -- your
# domain, your Razorpay keys, your SMTP credentials -- is left as a REPLACE_ME
# that the application will refuse to start with, so nothing can be forgotten
# quietly. Run `./scripts/generate-production-env.sh --check .env.production`
# afterwards to confirm nothing was left behind.
set -euo pipefail

secret() { openssl rand -hex 32; }
# Alphanumeric only: these end up in connection strings and shell env, where
# base64's / and + need escaping and eventually will not get it.
password() { LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 32; }

if [ "${1:-}" = "--check" ]; then
    file="${2:?usage: $0 --check <envfile>}"
    if remaining=$(grep -n "REPLACE_ME" "$file"); then
        echo "Not ready -- these still need real values:" >&2
        echo "$remaining" >&2
        exit 1
    fi
    echo "No placeholders left in $file"
    exit 0
fi

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }

cat <<EOF
# Generated by scripts/generate-production-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
#
# Treat this file as a credential. Do not commit it. Prefer loading these from a
# secrets manager and keeping the file only as the list of what must be set.

# ---- General ----------------------------------------------------------------
APP_NAME=ParkSpace
ENVIRONMENT=production
DEBUG=false
API_PREFIX=/api/v1
# Must be https, and must be the domain the browser actually uses: it goes into
# payment redirects and email links.
FRONTEND_URL=https://REPLACE_ME.example.com
CORS_ORIGINS=["https://REPLACE_ME.example.com"]
TIMEZONE=Asia/Kolkata

# ---- Infrastructure credentials ---------------------------------------------
POSTGRES_USER=parking
POSTGRES_PASSWORD=$(password)
POSTGRES_DB=parking
REDIS_PASSWORD=$(password)
# The CIDR of your load balancer / ingress. Anything wider than the real proxy
# makes every per-IP rate limit bypassable with an X-Forwarded-For header.
TRUSTED_PROXY_IPS=REPLACE_ME/32
API_WORKERS=4

# ---- Database ---------------------------------------------------------------
# Compose builds DATABASE_URL from POSTGRES_*. Set it explicitly only if the
# database lives outside this stack.
DB_ECHO=false

# ---- Redis ------------------------------------------------------------------
# Compose builds REDIS_URL from REDIS_PASSWORD. Required in production: without
# it, rate limiting is per-process and resets on every deploy.

# ---- Auth -------------------------------------------------------------------
# 32 bytes. The app refuses to start on anything shorter -- a short HMAC key
# weakens every token regardless of how unguessable it looks (RFC 7518 3.2).
JWT_SECRET=$(secret)
JWT_ALGORITHM=HS256
ACCESS_TOKEN_MINUTES=60
REFRESH_TOKEN_DAYS=30

# ---- Storage ----------------------------------------------------------------
STORAGE_BACKEND=local
MEDIA_ROOT=media
MEDIA_URL=/media
MAX_UPLOAD_BYTES=5242880

# ---- Payments ---------------------------------------------------------------
PAYMENT_GATEWAY=razorpay
RAZORPAY_KEY_ID=REPLACE_ME
RAZORPAY_KEY_SECRET=REPLACE_ME
RAZORPAY_WEBHOOK_SECRET=REPLACE_ME
MOCK_GATEWAY_SECRET=$(secret)
# Leave this off. It lets any renter mark their own booking paid.
ALLOW_SANDBOX_PAYMENTS=false

# ---- Email ------------------------------------------------------------------
EMAIL_BACKEND=smtp
EMAIL_FROM=ParkSpace <no-reply@REPLACE_ME.example.com>
SMTP_HOST=REPLACE_ME
SMTP_PORT=587
SMTP_USER=REPLACE_ME
SMTP_PASSWORD=REPLACE_ME
# Required whenever SMTP_PASSWORD is set; the app refuses to start otherwise.
SMTP_TLS=true

# ---- Geocoding --------------------------------------------------------------
GEOCODER_URL=https://nominatim.openstreetmap.org/search
# Nominatim's usage policy requires a real contact address here.
GEOCODER_USER_AGENT=parkspace/1.0 (REPLACE_ME@example.com)

# ---- Background maintenance -------------------------------------------------
MAINTENANCE_ENABLED=true
MAINTENANCE_INTERVAL_SECONDS=60

# ---- Rate limiting ----------------------------------------------------------
RATE_LIMIT_ENABLED=true

# ---- Deploy -----------------------------------------------------------------
# Migrations are a pre-deploy step, not a start-up step.
RUN_MIGRATIONS=false

# ---- Seed admin -------------------------------------------------------------
SEED_ADMIN_EMAIL=REPLACE_ME@example.com
SEED_ADMIN_PASSWORD=$(password)

# ---- Map --------------------------------------------------------------------
# Read at frontend BUILD time. Rebuild the web image to change it.
VITE_MAPTILER_KEY=REPLACE_ME
EOF
