import enum
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import (
    CheckConstraint,
    Computed,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import TSTZRANGE, UUID, ExcludeConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPkMixin, str_enum
from app.modules.parking.models import ParkingSpace, PricingUnit
from app.modules.users.models import User
from app.modules.vehicles.models import Vehicle


class BookingStatus(str, enum.Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    # Provider approval pending (only for listings with requires_approval).
    PENDING_APPROVAL = "PENDING_APPROVAL"
    CONFIRMED = "CONFIRMED"
    ACTIVE = "ACTIVE"
    # Past its end time with the car still in the bay and a top-up owed.
    OVERSTAYING = "OVERSTAYING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
    DISPUTED = "DISPUTED"
    REJECTED = "REJECTED"


# Statuses that occupy the slot. Kept in one place: the database exclusion
# constraint below and every availability query derive from this tuple.
BLOCKING_STATUSES: tuple[BookingStatus, ...] = (
    BookingStatus.PENDING_PAYMENT,
    BookingStatus.PENDING_APPROVAL,
    BookingStatus.CONFIRMED,
    BookingStatus.ACTIVE,
    # An overstaying car is physically in the bay. If this were left out, the
    # next renter could book a space with a vehicle still sitting in it.
    BookingStatus.OVERSTAYING,
    BookingStatus.DISPUTED,
)

# Statuses from which a renter may still cancel.
CANCELLABLE_STATUSES: tuple[BookingStatus, ...] = (
    BookingStatus.PENDING_PAYMENT,
    BookingStatus.PENDING_APPROVAL,
    BookingStatus.CONFIRMED,
    BookingStatus.ACTIVE,
)

_BLOCKING_SQL = ", ".join(f"'{s.value}'" for s in BLOCKING_STATUSES)


class Booking(UUIDPkMixin, TimestampMixin, Base):
    """A renter's reservation of one slot of a parking space for one period.

    Double-booking is prevented by `no_overlapping_bookings` below — a PostgreSQL
    exclusion constraint. Two concurrent transactions cannot both commit an
    overlapping period for the same slot regardless of what the application does,
    which is why booking creation never needs to trust a prior availability read.
    """

    __tablename__ = "bookings"
    __table_args__ = (
        CheckConstraint("end_at > start_at", name="end_after_start"),
        CheckConstraint("slot_index >= 0", name="slot_index_non_negative"),
        CheckConstraint("total_amount >= 0", name="total_non_negative"),
        ExcludeConstraint(
            ("parking_space_id", "="),
            ("slot_index", "="),
            ("period", "&&"),
            name="no_overlapping_bookings",
            using="gist",
            where=text(f"status IN ({_BLOCKING_SQL})"),
        ),
        Index("ix_bookings_renter_start", "renter_id", "start_at"),
        Index("ix_bookings_provider_start", "provider_id", "start_at"),
        Index("ix_bookings_status_start", "status", "start_at"),
    )

    # Short human-readable identifier shown on the confirmation, e.g. PS-7F3K9Q.
    reference: Mapped[str] = mapped_column(String(20), unique=True, index=True)

    renter_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="RESTRICT"), index=True
    )
    parking_space_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("parking_spaces.id", ondelete="RESTRICT"), index=True
    )
    # Denormalised from the space so provider dashboards don't need a join, and so
    # earnings survive a listing being reassigned.
    provider_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("providers.id", ondelete="RESTRICT"), index=True
    )
    vehicle_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("vehicles.id", ondelete="SET NULL")
    )
    # Plate snapshot: the booking must stay valid if the renter edits or deletes
    # the saved vehicle afterwards.
    vehicle_number: Mapped[str] = mapped_column(String(20))
    vehicle_type: Mapped[str] = mapped_column(String(20))

    # Which of the space's slots this booking occupies (0-based).
    slot_index: Mapped[int] = mapped_column(Integer, default=0)
    start_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True)
    end_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    # Generated by PostgreSQL so it can never disagree with start_at/end_at.
    period: Mapped[object] = mapped_column(
        TSTZRANGE, Computed("tstzrange(start_at, end_at, '[)')", persisted=True)
    )

    # --- Overstay. Frozen onto the booking as it accrues, so a later rate
    # change never rewrites what somebody already owed. ---
    overstay_minutes: Mapped[int] = mapped_column(Integer, default=0)
    overstay_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    overstay_paid_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    unit: Mapped[PricingUnit] = mapped_column(str_enum(PricingUnit))
    # Billable units (hours, days or months) the price was computed from.
    quantity: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    unit_price: Mapped[Decimal] = mapped_column(Numeric(10, 2))

    # --- Money. Every amount is frozen at booking time so later settings changes
    # never rewrite history. base = unit_price * quantity. ---
    base_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    platform_fee: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    tax_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    total_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2))
    commission_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    provider_earning: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    currency: Mapped[str] = mapped_column(String(3), default="INR")

    status: Mapped[BookingStatus] = mapped_column(
        str_enum(BookingStatus), default=BookingStatus.PENDING_PAYMENT, index=True
    )
    # Unpaid bookings stop blocking the slot after this moment.
    hold_expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), index=True)
    confirmed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    cancelled_by_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    cancellation_reason: Mapped[str | None] = mapped_column(Text)
    refund_amount: Mapped[Decimal] = mapped_column(Numeric(10, 2), default=0)
    renter_notes: Mapped[str | None] = mapped_column(Text)
    reminder_sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    renter: Mapped[User] = relationship(foreign_keys=[renter_id], lazy="joined")
    parking_space: Mapped[ParkingSpace] = relationship(lazy="joined")
    vehicle: Mapped[Vehicle | None] = relationship(lazy="joined")

    @property
    def is_blocking(self) -> bool:
        return self.status in BLOCKING_STATUSES


class ArrivalCode(UUIDPkMixin, Base):
    """A one-time code the provider reads out to a renter standing at the gate.

    The code is stored in the clear on purpose: the provider has to be able to
    re-read it if they reopen the app, so it cannot be a one-way hash. It is a
    six-digit value that lives for minutes, burns after a handful of wrong
    guesses, and grants nothing beyond flipping one booking to ACTIVE — so the
    exposure is small and bounded. It is deliberately NOT the booking reference,
    which appears in emails and dashboards and would therefore be guessable.
    """

    __tablename__ = "arrival_codes"
    __table_args__ = (
        # One live code per booking; re-requesting replaces the row.
        Index("uq_arrival_codes_booking", "booking_id", unique=True),
    )

    booking_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("bookings.id", ondelete="CASCADE"), index=True
    )
    code: Mapped[str] = mapped_column(String(10))
    # Set when the renter announced arrival, so the provider sees how long they
    # have been waiting and support can see who was left standing there.
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True))
    attempts: Mapped[int] = mapped_column(Integer, default=0)
    verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    # Where the renter said they were, for disputes about who was actually there.
    latitude: Mapped[float | None] = mapped_column(Numeric(9, 6))
    longitude: Mapped[float | None] = mapped_column(Numeric(9, 6))

    booking: Mapped["Booking"] = relationship()
